'use strict';

const PREVIEW_WIDTH = 500;
const PREVIEW_HEIGHT = 667;

const OUTPUT_WIDTH = 1242;
const OUTPUT_HEIGHT = 1656;

const DEFAULT_BRAND_TEXT = '极客狐';
const DEFAULT_WATERMARK_OPACITY = 0.1;
const DEFAULT_DEBOUNCE_DELAY = 300;
const DEFAULT_COVER_IMAGE = '';

module.exports = {
    PREVIEW_WIDTH,
    PREVIEW_HEIGHT,
    OUTPUT_WIDTH,
    OUTPUT_HEIGHT,
    DEFAULT_BRAND_TEXT,
    DEFAULT_WATERMARK_OPACITY,
    DEFAULT_DEBOUNCE_DELAY,
    DEFAULT_COVER_IMAGE
};
